apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ehiomm273-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ehiomm273-python 
  name: ehiomm273-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ehiomm273-python 
